from ..core.context import engine
from ..numerology import NumerologyEngine

num_engine = NumerologyEngine()

def generate_cosmic_id_svg(context):
    """Generates a beautiful SVG Cosmic ID card for sharing."""
    state = context.get_state()
    if not state: return "<svg></svg>"
    
    user = state["user"]
    planets = state["planets_birth"]
    
    # Gather data
    name = (user.email.split("@")[0] if user.email else "Cosmic Traveler").upper()
    if hasattr(user, "first_name") and user.first_name:
        name = user.first_name.upper()
        
    sun_sign = planets.get("Sun", {}).get("sign", "Unknown")
    moon_sign = planets.get("Moon", {}).get("sign", "Unknown")
    asc_sign = planets.get("Ascendant", {}).get("sign", "Unknown")
    

    dob = user.birth_date or "Unknown"
    dob_formatted = "Unknown"
    if dob != "Unknown":
        from datetime import datetime
        try:
            dob_formatted = datetime.strptime(dob, "%Y-%m-%d").strftime("%d-%m-%Y")
        except:
            dob_formatted = dob
    mulank = str(num_engine.calculate_mulank(dob_formatted)) if dob_formatted != "Unknown" else "?"
    bhagyank = str(num_engine.calculate_bhagyank(dob_formatted)) if dob_formatted != "Unknown" else "?"

    
    # SVG Template (PSBC Premium Aesthetic)
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 1080" width="1080" height="1080">
        <defs>
            <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stop-color="#1E1A38" />
                <stop offset="100%" stop-color="#0F0D1C" />
            </linearGradient>
            <style>
                .title {{ font-family: -apple-system, system-ui, sans-serif; font-weight: 800; font-size: 84px; fill: #ffffff; letter-spacing: -0.04em; }}
                .subtitle {{ font-family: -apple-system, system-ui, sans-serif; font-weight: 600; font-size: 32px; fill: #C8A86A; letter-spacing: 0.2em; text-transform: uppercase; }}
                .label {{ font-family: -apple-system, system-ui, sans-serif; font-weight: 700; font-size: 24px; fill: #8a7e68; letter-spacing: 0.1em; text-transform: uppercase; }}
                .value {{ font-family: -apple-system, system-ui, sans-serif; font-weight: 500; font-size: 48px; fill: #ffffff; }}
                .number {{ font-family: -apple-system, system-ui, sans-serif; font-weight: 800; font-size: 140px; fill: #C8A86A; letter-spacing: -0.05em; }}
                .brand {{ font-family: -apple-system, system-ui, sans-serif; font-weight: 700; font-size: 24px; fill: #ffffff; letter-spacing: 0.1em; opacity: 0.5; }}
            </style>
        </defs>
        
        <!-- Background -->
        <rect width="1080" height="1080" fill="url(#bg)" />
        
        <!-- Subtle border -->
        <rect x="40" y="40" width="1000" height="1000" fill="none" stroke="rgba(200, 168, 106, 0.3)" stroke-width="2" rx="20" />
        
        <!-- Header -->
        <text x="80" y="160" class="subtitle">COSMIC ID</text>
        <text x="80" y="260" class="title">{name}</text>
        
        <!-- Core Planets -->
        <text x="80" y="420" class="label">SUN SIGN</text>
        <text x="80" y="480" class="value">{sun_sign}</text>
        
        <text x="440" y="420" class="label">MOON SIGN</text>
        <text x="440" y="480" class="value">{moon_sign}</text>
        
        <text x="800" y="420" class="label">ASCENDANT</text>
        <text x="800" y="480" class="value">{asc_sign}</text>
        
        <!-- Line Separator -->
        <line x1="80" y1="560" x2="1000" y2="560" stroke="rgba(255,255,255,0.1)" stroke-width="2" />
        
        <!-- Numerology -->
        <text x="80" y="660" class="label">DRIVER NUMBER (MULANK)</text>
        <text x="80" y="820" class="number">{mulank}</text>
        
        <text x="560" y="660" class="label">CONDUCTOR (BHAGYANK)</text>
        <text x="560" y="820" class="number">{bhagyank}</text>
        
        <!-- Footer -->
        <text x="80" y="980" class="brand">GENERATED BY COSMIC OS</text>
        <text x="760" y="980" class="brand" fill="#635bff">EXECUTIVE INTELLIGENCE</text>
    </svg>"""
    return svg