import os
import json
from google_auth_oauthlib.flow import Flow
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from fastapi import Request as FastAPIRequest, HTTPException
from fastapi.responses import RedirectResponse

SCOPES = [
    'openid',
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/calendar.events',
    'https://www.googleapis.com/auth/gmail.readonly'
]

def _build_client_config():
    """Build OAuth config from env vars, falling back to credentials.json."""
    client_id     = os.getenv("GOOGLE_CLIENT_ID")
    client_secret = os.getenv("GOOGLE_CLIENT_SECRET")
    if client_id and client_secret:
        return {
            "web": {
                "client_id":     client_id,
                "client_secret": client_secret,
                "auth_uri":      "https://accounts.google.com/o/oauth2/auth",
                "token_uri":     "https://oauth2.googleapis.com/token",
            }
        }
    if os.path.exists("credentials.json"):
        with open("credentials.json", "r") as f:
            return json.load(f)
    return None

class GoogleAuthManager:
    def __init__(self):
        self.client_config = _build_client_config()

    def get_login_url(self, redirect_uri: str):
        if not self.client_config:
            raise HTTPException(status_code=500, detail="Google OAuth credentials not configured.")
        flow = Flow.from_client_config(self.client_config, scopes=SCOPES, redirect_uri=redirect_uri)
        authorization_url, state = flow.authorization_url(
            access_type='offline',
            include_granted_scopes='true'
        )
        # PKCE: code_verifier is auto-generated by newer google-auth-oauthlib versions
        code_verifier = getattr(flow, 'code_verifier', None)
        return authorization_url, state, code_verifier

    def exchange_code(self, code: str, redirect_uri: str, code_verifier: str = None):
        flow = Flow.from_client_config(self.client_config, scopes=SCOPES, redirect_uri=redirect_uri)
        if code_verifier:
            flow.code_verifier = code_verifier
        flow.fetch_token(code=code)
        credentials = flow.credentials
        result = credentials_to_dict(credentials)
        try:
            import requests as _req
            resp = _req.get(
                "https://www.googleapis.com/oauth2/v2/userinfo",
                headers={"Authorization": f"Bearer {credentials.token}"},
                timeout=5,
            )
            result["email"] = resp.json().get("email", "")
        except Exception:
            result["email"] = ""
        return result

def credentials_to_dict(credentials):
    return {
        'token': credentials.token,
        'refresh_token': credentials.refresh_token,
        'token_uri': credentials.token_uri,
        'client_id': credentials.client_id,
        'client_secret': credentials.client_secret,
        'scopes': credentials.scopes
    }
